Make Test report a separate job

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -39,6 +39,21 @@ permissions:
   pull-requests: read # allows SonarCloud to decorate PRs with analysis results
 
 jobs:
+  build:
+    name: Build and Run Tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+      - name: Build and Run Tests
+        run: mvn -B test --file pom.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+          token: ${{ secrets.GITHUB_TOKEN }}
+          
   Analysis:
     runs-on: ubuntu-latest
     steps:
@@ -49,9 +64,6 @@ jobs:
           java-version: '11'
           distribution: 'temurin'
           cache: maven
-      
-      - name: JUnit Report Action
-        uses: mikepenz/action-junit-report@v3.7.5
     
       - name: Jacoco Test Report
         run: mvn -B test --file pom.xml -Pcoverage
